[theme]
primaryColor = "#F39C12"
backgroundColor = "#2E3B4E"  # Dark background color
secondaryBackgroundColor = "#192A3E"  # Slightly lighter background
textColor = "#FFFFFF"  # White text for dark theme
font = "sans serif"

